CREATE DATABASE CV;

USE CV;

CREATE TABLE courses (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CourseCode VARCHAR(10) NOT NULL,
    CourseName VARCHAR(100) NOT NULL,
    Syllabus TEXT NOT NULL,
    Progression TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);